-- Supabase schema for ReWork Crowdfunds Donations

CREATE TABLE IF NOT EXISTS public.crowdfund_donations (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  crowdfund_id integer NOT NULL REFERENCES public.crowdfunds(id) ON DELETE CASCADE,
  donor_public_key text NOT NULL,
  amount bigint NOT NULL,
  escrow_contract_id text NOT NULL, -- The unique TW Escrow ID for this specific donation
  status text NOT NULL DEFAULT 'funded', -- 'funded', 'released', 'refunded'
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.crowdfund_donations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public insert to donations" ON public.crowdfund_donations FOR INSERT TO public WITH CHECK (true);
CREATE POLICY "Allow public select of donations" ON public.crowdfund_donations FOR SELECT TO public USING (true);
CREATE POLICY "Allow public update to donations" ON public.crowdfund_donations FOR UPDATE TO public USING (true);
